workflows:
  default:
    name: Default Workflow
    environment:
      groups:
        - default
      vars:
        BUNDLE_ID: "com.dadoseconomicos6.app"
    scripts:
      - name: Set up code signing
        script: |
          # 1. inicializa o keychain que o codemagic vai usar
          keychain initialize
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create
          
          # 2. adiciona os arquivos que voce subiu manualmente para o keychain
          keychain add-certificates
          xcode-project use-profiles
          
      - name: Build Flutter app
        script: |
            flutter build ios --release

