library(uuid)


# criar a funcao que simula a classe cadastroSeries existente no app
cadastroSeries <- function(numero, nome, nomeCompleto, descricao, formato, fonte, urlAPI, idAssunto, periodicidade, metrica, nivelGeografico, localidades,
                           categoria){
  
  return(paste0("cadastroSeries(",numero,",'",nome,"','",nomeCompleto,"','",descricao,"','",formato,"','",fonte,"','",urlAPI,"',",idAssunto,",'",periodicidade,"','",metrica,
                "','",nivelGeografico,"','",localidades,"','",categoria,"'),"))
  
}


listaSeries <- list(
  cadastroSeries(300000,
                 'Novo Caged',
                 'Novo Caged - Total',
                 'Estoque total de empregos formais, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28763/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Total'),
  cadastroSeries(300001,
                 'Novo Caged',
                 'Novo Caged - Agropecuária',
                 'Estoque de empregos formais da agropecuária, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28764/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Agropecuária'),
  cadastroSeries(300002,
                 'Novo Caged',
                 'Novo Caged - Indústrias extrativas',
                 'Estoque de empregos formais das indústrias extrativas, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28765/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Indústrias extrativas'),
  cadastroSeries(300003,
                 'Novo Caged',
                 'Novo Caged - Indústrias de transformação',
                 'Estoque de empregos formais das indústrias de transformação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28766/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Indústrias de transformação'),
  cadastroSeries(300004,
                 'Novo Caged',
                 'Novo Caged - Serviços Industriais de Utilidade Pública (SIUP)',
                 'Estoque de empregos formais no setor de Serviços Industriais de Utilidade Pública (SIUP), segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28767/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Serviços Industriais de Utilidade Pública (SIUP)'),
  cadastroSeries(300005,
                 'Novo Caged',
                 'Novo Caged - Eletricidade e gás',
                 'Estoque de empregos formais no setor de eletricidade e gás, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28768/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Eletricidade e gás'),
  cadastroSeries(300006,
                 'Novo Caged',
                 'Novo Caged - Água, esgoto, atividades de gestão de resíduos e descontaminação',
                 'Estoque de empregos formais no setor de água, esgoto, atividades de gestão de resíduos e descontaminação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28769/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Água, esgoto, atividades de gestão de resíduos e descontaminação'),
  cadastroSeries(300007,
                 'Novo Caged',
                 'Novo Caged - Construção',
                 'Estoque de empregos formais no setor de construção, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28770/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Construção'),
  cadastroSeries(300008,
                 'Novo Caged',
                 'Novo Caged - Comércio',
                 'Estoque de empregos formais no comércio, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28771/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Comércio'),
  cadastroSeries(300009,
                 'Novo Caged',
                 'Novo Caged - Serviços',
                 'Estoque de empregos formais no setor de serviços, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28772/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Serviços'),
  cadastroSeries(300010,
                 'Novo Caged',
                 'Novo Caged - Transporte, armazenamento e correio',
                 'Estoque de empregos formais no setor de transporte, armazenamento e correio, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28773/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Transporte, armazenamento e correio'),
  cadastroSeries(300011,
                 'Novo Caged',
                 'Novo Caged - Alojamento e alimentação',
                 'Estoque de empregos formais no setor de alojamento e alimentação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28774/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Alojamento e alimentação'),
  cadastroSeries(300012,
                 'Novo Caged',
                 'Novo Caged - Informação e comunicação',
                 'Estoque de empregos formais no setor de informação e comunicação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28775/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Informação e comunicação'),
  cadastroSeries(300013,
                 'Novo Caged',
                 'Novo Caged - Atividades financeiras e seguros',
                 'Estoque de empregos formais no setor de atividades financeiras e seguros, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28776/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades financeiras e seguros'),
  cadastroSeries(300014,
                 'Novo Caged',
                 'Novo Caged - Atividades imobiliárias',
                 'Estoque de empregos formais no setor de atividades imobiliárias, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28777/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades imobiliárias'),
  cadastroSeries(300015,
                 'Novo Caged',
                 'Novo Caged - Atividades profissionais, científicas e técnicas',
                 'Estoque de empregos formais no setor de atividades profissionais, científicas e técnicas, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28778/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades profissionais, científicas e técnicas'),
  cadastroSeries(300016,
                 'Novo Caged',
                 'Novo Caged - Atividades administrativas e serviços complementares',
                 'Estoque de empregos formais no setor de atividades administrativas e serviços complementares, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28779/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades administrativas e serviços complementares'),
  cadastroSeries(300017,
                 'Novo Caged',
                 'Novo Caged - Administração pública, defesa e seguridade social',
                 'Estoque de empregos formais no setor de administração pública, defesa e seguridade social, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28780/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Administração pública, defesa e seguridade social'),
  cadastroSeries(300018,
                 'Novo Caged',
                 'Novo Caged - Educação',
                 'Estoque de empregos formais no setor de educação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28781/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Educação'),
  cadastroSeries(300019,
                 'Novo Caged',
                 'Novo Caged - Saúde e serviços sociais',
                 'Estoque de empregos formais no setor de saúde e serviços sociais, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28782/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Saúde e serviços sociais'),
  cadastroSeries(300020,
                 'Novo Caged',
                 'Novo Caged - Outras atividades de serviços',
                 'Estoque de empregos formais no setor de outras atividades de serviços, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28783/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Sem ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Outras atividades de serviços'),
  cadastroSeries(300021,
                 'Novo Caged',
                 'Novo Caged - Total - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28784/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Total'),
  cadastroSeries(300022,
                 'Novo Caged',
                 'Novo Caged - Agropecuária - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de agropecuária, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28785/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Agropecuária'),
  cadastroSeries(300023,
                 'Novo Caged',
                 'Novo Caged - Indústrias extrativas - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de indústrias extrativas, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28786/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Indústrias extrativas'),
  cadastroSeries(300024,
                 'Novo Caged',
                 'Novo Caged - Indústrias de transformação - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de indústrias de transformação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28787/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Indústrias de transformação'),
  cadastroSeries(300025,
                 'Novo Caged',
                 'Novo Caged - Serviços Industriais de Utilidade Pública (SIUP) - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de Serviços Industriais de Utilidade Pública (SIUP), segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28788/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Serviços Industriais de Utilidade Pública (SIUP)'),
  cadastroSeries(300026,
                 'Novo Caged',
                 'Novo Caged - Eletricidade e gás - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de eletricidade e gás, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28789/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Eletricidade e gás'),
  cadastroSeries(300027,
                 'Novo Caged',
                 'Novo Caged - Água, esgoto, atividades de gestão de resíduos e descontaminação - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de eletricidade e gás, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28790/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Água, esgoto, atividades de gestão de resíduos e descontaminação'),
  cadastroSeries(300028,
                 'Novo Caged',
                 'Novo Caged - Construção - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de construção, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28791/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Construção'),
  cadastroSeries(300029,
                 'Novo Caged',
                 'Novo Caged - Comércio - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de comércio, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28792/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Comércio'),
  cadastroSeries(300030,
                 'Novo Caged',
                 'Novo Caged - Serviços - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de serviços, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28793/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Serviços'),
  cadastroSeries(300031,
                 'Novo Caged',
                 'Novo Caged - Transporte, armazenamento e correio - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de transporte, armazenamento e correio, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28794/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Transporte, armazenamento e correio'),
  cadastroSeries(300032,
                 'Novo Caged',
                 'Novo Caged - Alojamento e alimentação - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de alojamento e alimentação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28795/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Alojamento e alimentação'),
  cadastroSeries(300033,
                 'Novo Caged',
                 'Novo Caged - Informação e comunicação - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de informação e comunicação, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28796/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Informação e comunicação'),
  cadastroSeries(300034,
                 'Novo Caged',
                 'Novo Caged - Atividades financeiras e seguros - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de atividades financeiras e seguros, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28797/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades financeiras e seguros'),
  cadastroSeries(300035,
                 'Novo Caged',
                 'Novo Caged - Atividades imobiliárias - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de atividades imobiliárias, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28798/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades imobiliárias'),
  cadastroSeries(300036,
                 'Novo Caged',
                 'Novo Caged - Atividades profissionais, científicas e técnicas - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de atividades profissionais, científicas e técnicas, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28799/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades profissionais, científicas e técnicas'),
  cadastroSeries(300037,
                 'Novo Caged',
                 'Novo Caged - Atividades administrativas e serviços complementares - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de atividades administrativas e serviços complementares, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28800/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Atividades administrativas e serviços complementares'),
  cadastroSeries(300038,
                 'Novo Caged',
                 'Novo Caged - Administração pública, defesa e seguridade social - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de administração pública, defesa e seguridade social, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28801/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Administração pública, defesa e seguridade social'),
  cadastroSeries(300039,
                 'Novo Caged',
                 'Novo Caged - Educação - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de administração pública, defesa e seguridade social, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28802/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Educação'),
  cadastroSeries(300040,
                 'Novo Caged',
                 'Novo Caged - Saúde e serviços sociais - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de saúde e serviços sociais, defesa e seguridade social, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28803/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Saúde e serviços sociais'),
  cadastroSeries(300041,
                 'Novo Caged',
                 'Novo Caged - Outras atividades de serviços - Dados dessazonalizados',
                 'Estoque total dessazonalizado de empregos formais do setor de outras atividades de serviços, defesa e seguridade social, segundo o Novo Cadastro Geral de Empregados e Desempregados (Novo Caged) da Secretaria Especial de Previdência e Trabalho do Ministério da Economia. O estoque do emprego formal é calculado a partir do estoque base do primeiro dia útil do ano corrente e evoluído a partir dos saldos mensais de admissão líquida de demissão incorporando informações de declarações recebidas fora do prazo.',
                 'Unidades',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28804/dados?formato=json',
                 3,
                 'mensal',
                 'Estoque de empregos formais - Com ajuste sazonal',
                 'Brasil',
                 'Brasil',
                 'Outras atividades de serviços'),
  cadastroSeries(300042,
                 'Dados de emprego da PNADC',
                 'Pessoas em idade de trabalhar - PNADC',
                 'Pessoas de 14 anos ou mais de idade na data de referência, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC).',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24370/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Pessoas em idade de trabalhar'),
  cadastroSeries(300043,
                 'Dados de emprego da PNADC',
                 'Empregados no setor privado e público - PNADC',
                 'Empregados no setor privado e público, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado do setor privado: pessoa que trabalhava para um empregador (pessoa física ou jurídica) do setor privado, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo, exclui-se trabalhadores domésticos. Empregado do setor público: pessoa que trabalhava para o governo, em qualquer esfera: federal, estadual ou municipal, que abrange, além das entidades da administração direta, as fundações, as autarquias, as empresas públicas e as empresas de economia mista. Nesse subgrupo, incluiu-se pessoa que exercia mandato eletivo como vereador, deputado, prefeito etc. Nesse subgrupo, inclui-se também servidores estatutários e militares.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24371/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregados no setor privado e público'),
  cadastroSeries(300044,
                 'Dados de emprego da PNADC',
                 'Empregados no setor público - PNADC',
                 'Empregados no setor público, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado do setor público: pessoa que trabalhava para o governo, em qualquer esfera: federal, estadual ou municipal, que abrange, além das entidades da administração direta, as fundações, as autarquias, as empresas públicas e as empresas de economia mista. Nesse subgrupo, incluiu-se pessoa que exercia mandato eletivo como vereador, deputado, prefeito etc. Nesse subgrupo, inclui-se também servidores estatutários e militares.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24372/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregados no setor público'),
  cadastroSeries(300045,
                 'Dados de emprego da PNADC',
                 'Empregado por conta própria - PNADC',
                 'Empregados por conta própria, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado por conta própria: pessoa que trabalhava explorando o seu próprio empreendimento, sozinha ou com sócio, sem ter empregado e contando, ou não, com a ajuda de trabalhador familiar auxiliar.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24373/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregado por conta própria'),
  cadastroSeries(300046,
                 'Dados de emprego da PNADC',
                 'Empregadores - PNADC',
                 'Quantidade de empregadores, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregador: pessoa que trabalhava explorando o seu próprio empreendimento, com pelo menos um empregado.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24374/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregadores'),
  cadastroSeries(300047,
                 'Dados de emprego da PNADC',
                 'Empregados no setor privado - Com carteira - PNADC',
                 'Quantidade de empregados no setor privado com carteira assinada, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado do setor privado com carteira: pessoas que trabalhavam para um empregador (pessoa física ou jurídica) do setor privado, com carteira de trabalho assinada, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24375/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregados no setor privado - Com carteira'),
  cadastroSeries(300048,
                 'Dados de emprego da PNADC',
                 'Empregados no setor privado - Sem Carteira - PNADC',
                 'Quantidade de empregados no setor privado sem carteira assinada, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado do setor privado com carteira: pessoas que trabalhavam para um empregador (pessoa física ou jurídica) do setor privado, com carteira de trabalho assinada, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24376/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregados no setor privado - Sem carteira'),
  cadastroSeries(300049,
                 'Dados de emprego da PNADC',
                 'Empregados no setor privado - Total - PNADC',
                 'Quantidade total de empregados no setor privado, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Empregado do setor privado com carteira: pessoas que trabalhavam para um empregador (pessoa física ou jurídica) do setor privado, com carteira de trabalho assinada, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24377/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Empregados no setor privado - Total'),
  cadastroSeries(300050,
                 'Dados de emprego da PNADC',
                 'População na força de trabalho - PNADC',
                 'População na força de trabalho, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). A população na força de trabalho na semana de referência compreendem as pessoas ocupadas e as pessoas desocupadas nesse período. População ocupada: São classificadas como ocupadas na semana de referência as pessoas que, nesse período, trabalharam pelo menos uma hora completa em trabalho remunerado em dinheiro, produtos, mercadorias ou benefícios (moradia, alimentação, roupas, treinamento etc.) ou em trabalho sem remuneração direta em ajuda à atividade econômica de membro do domicílio ou, ainda, as pessoas que tinham trabalho remunerado do qual estavam temporariamente afastadas nessa semana. Consideram-se como ocupadas temporariamente afastadas de trabalho remunerado as pessoas que não trabalharam durante pelo menos uma hora completa na semana de referência por motivo de: férias, folga, jornada de trabalho variável, licença maternidade e fatores ocasionais. Assim, também foram consideradas as pessoas que, na data de referência, estavam, por período inferior a 4 meses: afastadas do trabalho em licença remunerada por motivo de doença ou acidente da própria pessoa ou outro tipo de licença remunerada; afastadas do próprio empreendimento sem serem remuneradas por instituto de previdência; em greve ou paralisação. Além disso, também, foram consideradas ocupadas as pessoas afastadas por motivos diferentes dos já citados, desde que tivessem continuado a receber ao menos uma parte do pagamento e o período transcorrido do afastamento fosse inferior a 4 meses. População desocupada: São classificadas como desocupadas na semana de referência as pessoas não ocupadas nesse período, que tomaram alguma providência efetiva para conseguir um trabalho no período de referência de 30 dias e que estavam disponíveis para iniciar um trabalho na semana de referência. Também são classificadas como desocupadas as pessoas não ocupadas e disponíveis para iniciar um trabalho na semana de referência que, no entanto, não tomaram providência efetiva para conseguir trabalho no período de referência de 30 dias porque já haviam conseguido trabalho para começar após a semana de referência.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24378/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'População na força de trabalho'),
  cadastroSeries(300051,
                 'Dados de emprego da PNADC',
                 'Pessoas ocupadas - PNADC',
                 'Pessoas ocupadas, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). População ocupada: São classificadas como ocupadas na semana de referência as pessoas que, nesse período, trabalharam pelo menos uma hora completa em trabalho remunerado em dinheiro, produtos, mercadorias ou benefícios (moradia, alimentação, roupas, treinamento etc.) ou em trabalho sem remuneração direta em ajuda à atividade econômica de membro do domicílio ou, ainda, as pessoas que tinham trabalho remunerado do qual estavam temporariamente afastadas nessa semana. Consideram-se como ocupadas temporariamente afastadas de trabalho remunerado as pessoas que não trabalharam durante pelo menos uma hora completa na semana de referência por motivo de: férias, folga, jornada de trabalho variável, licença maternidade e fatores ocasionais. Assim, também foram consideradas as pessoas que, na data de referência, estavam, por período inferior a 4 meses: afastadas do trabalho em licença remunerada por motivo de doença ou acidente da própria pessoa ou outro tipo de licença remunerada; afastadas do próprio empreendimento sem serem remuneradas por instituto de previdência; em greve ou paralisação. Além disso, também, foram consideradas ocupadas as pessoas afastadas por motivos diferentes dos já citados, desde que tivessem continuado a receber ao menos uma parte do pagamento e o período transcorrido do afastamento fosse inferior a 4 meses.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24379/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Pessoas ocupadas'),
  cadastroSeries(300052,
                 'Dados de emprego da PNADC',
                 'Pessoas desocupadas - PNADC',
                 'Pessoas desocupadas, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). População desocupada: São classificadas como desocupadas na semana de referência as pessoas não ocupadas nesse período, que tomaram alguma providência efetiva para conseguir um trabalho no período de referência de 30 dias e que estavam disponíveis para iniciar um trabalho na semana de referência. Também são classificadas como desocupadas as pessoas não ocupadas e disponíveis para iniciar um trabalho na semana de referência que, no entanto, não tomaram providência efetiva para conseguir trabalho no período de referência de 30 dias porque já haviam conseguido trabalho para começar após a semana de referência.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24380/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'Pessoas desocupadas'),
  cadastroSeries(300053,
                 'Dados de emprego da PNADC',
                 'População ocupada com rendimento',
                 'População ocupada com rendimento, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). População ocupada com rendimento: São classificadas como ocupadas na semana de referência as pessoas que, nesse período, trabalharam pelo menos uma hora completa em trabalho remunerado em dinheiro, produtos, mercadorias ou benefícios (moradia, alimentação, roupas, treinamento etc.) ou as pessoas que tinham trabalho remunerado do qual estavam temporariamente afastadas nessa semana.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28543/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'População ocupada com rendimento'),
  cadastroSeries(300054,
                 'Dados de emprego da PNADC',
                 'População ocupada com rendimento',
                 'População ocupada com rendimento, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). População ocupada com rendimento: São classificadas como ocupadas na semana de referência as pessoas que, nesse período, trabalharam pelo menos uma hora completa em trabalho remunerado em dinheiro, produtos, mercadorias ou benefícios (moradia, alimentação, roupas, treinamento etc.) ou as pessoas que tinham trabalho remunerado do qual estavam temporariamente afastadas nessa semana.',
                 'Unidades (mil)',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28543/dados?formato=json',
                 3,
                 'mensal',
                 'Unidades (mil)',
                 'Brasil',
                 'Brasil',
                 'População ocupada com rendimento'),
  cadastroSeries(300055,
                 'Salário mínimo',
                 'Salário mínimo',
                 'Salário mínimo vigente.',
                 'Unidade monetária vigente ao final de cada mês',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1619/dados?formato=json',
                 3,
                 'mensal',
                 'Unidade monetária vigente ao final de cada mês',
                 'Brasil',
                 'Brasil',
                 'Unidade monetária vigente ao final de cada mês'),
  cadastroSeries(300056,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real efetivo de todos os trabalhos - PNADC',
                 'Rendimento médio real efetivo de todos os trabalhos, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento médio real efetivamente recebido em todos os trabalhos pelos ocupados: É o rendimento bruto real médio efetivamente recebido no mês de referência em todos os trabalhos que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo – IPCA.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24381/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real efetivo de todos os trabalhos'),
  cadastroSeries(300057,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24382/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas'),
  cadastroSeries(300058,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Com carteira - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas com carteira assinada, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Empregado do setor privado com carteira: pessoa que trabalhava para um empregador (pessoa física ou jurídica) do setor privado, com carteira de trabalho assinada, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24383/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Com carteira'),
  cadastroSeries(300059,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Sem carteira - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas sem carteira assinada, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24384/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Sem carteira'),
  cadastroSeries(300060,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor privado - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas do setor privado, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Empregado do setor privado: pessoa que trabalhava para um empregador (pessoa física ou jurídica) do setor privado, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos. Nesse subgrupo inclui-se as categorias do emprego com e sem carteira de trabalho assinada.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24385/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor privado'),
  cadastroSeries(300061,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor público - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas do setor público, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Empregado do setor público: pessoa que trabalhava para o governo, em qualquer esfera: federal, estadual ou municipal, que abrange, além das entidades da administração direta, as fundações, as autarquias, as empresas públicas e as empresas de economia mista. Nesse subgrupo, incluiu-se pessoa que exercia mandato eletivo como vereador, deputado, prefeito etc.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24386/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor público'),
  cadastroSeries(300062,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Conta própria - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas por conta própria, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Conta própria: pessoa que trabalhava explorando o seu próprio empreendimento, sozinha ou com sócio, sem ter empregado e contando, ou não, com a ajuda de trabalhador familiar auxiliar.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24387/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Conta própria'),
  cadastroSeries(300063,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Empregadores - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas que são empregadores, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Empregador: pessoa que trabalhava explorando o seu próprio empreendimento, com pelo menos um empregado.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24388/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Empregadores'),
  cadastroSeries(300064,
                 'Dados de rendimento da PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor privado e público - PNADC',
                 'Rendimento médio real habitual das pessoas ocupadas no setor privado e público, segundo a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Rendimento médio real habitualmente recebido no trabalho principal pelos ocupados: É o rendimento bruto real médio habitualmente recebido no trabalho principal que as pessoas ocupadas com rendimento tinham na semana referência, a preços do mês do meio do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA. Empregado do setor privado: pessoa que trabalhava para um empregador (pessoa física ou jurídica) do setor privado, geralmente obrigando-se ao cumprimento de uma jornada de trabalho e recebendo em contrapartida uma remuneração em dinheiro, mercadorias, produtos ou benefícios (moradia, alimentação, roupas, treinamento etc.). Nesse subgrupo, incluiu-se o sacerdote, o ministro de igreja, o pastor, o rabino, o frade, a freira e outros clérigos. Nesse subgrupo exclui-se trabalhadores domésticos. Nesse subgrupo inclui-se as categorias do emprego com e sem carteira de trabalho assinada. Empregado do setor público: pessoa que trabalhava para o governo, em qualquer esfera: federal, estadual ou municipal, que abrange, além das entidades da administração direta, as fundações, as autarquias, as empresas públicas e as empresas de economia mista. Nesse subgrupo, incluiu-se pessoa que exercia mandato eletivo como vereador, deputado, prefeito etc.',
                 'R$',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24399/dados?formato=json',
                 3,
                 'mensal',
                 'R$',
                 'Brasil',
                 'Brasil',
                 'Rendimento médio real habitual das pessoas ocupadas - Setor privado e público'),
  cadastroSeries(300065,
                 'Massa real efetiva de todos os trabalhos',
                 'Massa real efetiva de todos os trabalhos',
                 'Massa de rendimento de todos os trabalhos, efetivamente recebido por mês, pelas pessoas de 14 anos ou mais de idade, ocupadas na semana de referência, com rendimento de trabalho - Brasil. Rendimento efetivo: O rendimento efetivo consiste no rendimento de fato recebido em qualquer posição na ocupação, no mês de referência, incluindo todos os pagamentos que não tenham caráter contínuo e considerando os descontos por ausências no trabalho.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28544/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'R$ milhões'),
  cadastroSeries(300066,
                 'Massa de rendimento real habitual de todos os trabalhos',
                 'Massa de rendimento real habitual de todos os trabalhos',
                 'Massa de rendimento de todos os trabalhos, habitualmente recebido por mês, pelas pessoas de 14 anos ou mais de idade, ocupadas na semana de referência, com rendimento de trabalho - Brasil. Rendimento habitual: O rendimento habitual consiste no rendimento recebido por empregados, empregadores e trabalhadores por conta própria, mensalmente, sem acréscimos extraordinários ou descontos esporádicos. Para o empregado, o rendimento mensal habitualmente recebido exclui todas as parcelas que não tenham caráter contínuo (bonificação anual, salário atrasado, horas extras, participação anual nos lucros, 13o salário, 14o salário, adiantamento de salário, etc.) e não considera os descontos ocasionais (faltas, parte do 13º salário antecipado, prejuízo eventual causado ao empreendimento etc.). Caso o rendimento recebido de empregado, de trabalhador por conta própria e de empregador seja variável, considera-se o rendimento habitual aquele em média recebido pela pessoa no período em que realizava o trabalho declarado na semana de referência. Quando a remuneração varia em função do período ou estação do ano, considera-se o rendimento mensal que a pessoa ganha habitualmente nesse período sazonal. Rendimento médio real habitualmente recebido em todos os trabalhos pelos ocupados: É o rendimento bruto real médio habitualmente recebido em todos os trabalhos que as pessoas ocupadas com rendimento tinham na semana referência, a preços médios do trimestre mais recente que está sendo divulgado. O deflator utilizado para isso é o Índice de Preços ao Consumidor Amplo - IPCA.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28545/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'R$ milhões'),
  cadastroSeries(300067,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29023/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Total'),
  cadastroSeries(300068,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – restrita',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior. A RNDBF restrita exclui o excedente operacional bruto e as rendas de propriedades, que são parcelas de renda, em teoria, menos correlacionadas com o ciclo econômico ou que não são tipicamente destinadas ao consumo imediato. RNDBF restrita = RT+BS-IRP-CS-OTC',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29024/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Restrita'),
  cadastroSeries(300069,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – deflacionada',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29025/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Total - deflacionada'),
  cadastroSeries(300070,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – restrita – deflacionada',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior. A RNDBF restrita exclui o excedente operacional bruto e as rendas de propriedades, que são parcelas de renda, em teoria, menos correlacionadas com o ciclo econômico ou que não são tipicamente destinadas ao consumo imediato. RNDBF restrita = RT+BS-IRP-CS-OTC',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29026/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Restrita - deflacionada'),
  cadastroSeries(300071,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – total – deflacionada, com ajuste sazonal',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29027/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Total - deflacionada, com ajuste sazonal'),
  cadastroSeries(300072,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – restrita – deflacionada, com ajuste sazonal',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior. A RNDBF restrita exclui o excedente operacional bruto e as rendas de propriedades, que são parcelas de renda, em teoria, menos correlacionadas com o ciclo econômico ou que não são tipicamente destinadas ao consumo imediato. RNDBF restrita = RT+BS-IRP-CS-OTC',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29028/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Restrita - deflacionada, com ajuste sazonal'),
  cadastroSeries(300073,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – total – acumulada em 12 meses',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior.',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29029/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Total - acumulada em 12 meses'),
  cadastroSeries(300074,
                 'Renda disponível das famílias',
                 'Renda disponível das famílias – restrita – acumulada em 12 meses',
                 'A Renda Nacional Disponível Bruta das Famílias - RNDBF - soma os rendimentos obtidos pelo uso de fatores de produção (trabalho e capital) e as transferências recebidas descontadas das transferências pagas. Mais especificamente, a RNDBF considera as seguintes parcelas de rendas das famílias, obtidas nas Contas Econômicas Integradas (CEI) do SCN: RNDBF = RT+EOB+RP+BS-IRP-CS-OTC. Onde: RT = Remuneração do trabalho; EOB = Excedente operacional bruto (renda de aluguel); RP = Rendas de propriedades; BS = Benefícios sociais; IRP = Impostos sobre renda e propriedade; CS = Contribuições sociais; OTC = Outras transferências correntes. A remuneração do trabalho inclui os salários dos empregados e o rendimento misto bruto; o excedente operacional bruto das famílias corresponde principalmente às rendas de aluguéis efetivo e imputado; as rendas de propriedade incluem juros líquidos recebidos, rendas distribuídas das empresas para as famílias e rendas de investimentos, menos as rendas pagas pelo uso de recursos naturais ; e os benefícios sociais somam os benefícios de seguridade social, outros benefícios de seguro social e benefícios de assistência social. Desse total, são deduzidos os impostos sobre renda e patrimônio, as contribuições sociais das famílias e outras transferências correntes líquidas realizadas pelas famílias para os demais setores institucionais da economia e para o exterior. A RNDBF restrita exclui o excedente operacional bruto e as rendas de propriedades, que são parcelas de renda, em teoria, menos correlacionadas com o ciclo econômico ou que não são tipicamente destinadas ao consumo imediato. RNDBF restrita = RT+BS-IRP-CS-OTC',
                 'R$ milhões',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29030/dados?formato=json',
                 3,
                 'mensal',
                 'R$ milhões',
                 'Brasil',
                 'Brasil',
                 'Restrita - acumulada em 12 meses'),
  cadastroSeries(300075,
                 'Dados de emprego da PNADC',
                 'Taxa de desocupação - PNADC',
                 'Taxa de desocupação, de acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua (PNADC). Representa o percentual de pessoas desocupadas em relação às pessoas na força de trabalho.',
                 '%',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.24369/dados?formato=json',
                 3,
                 'mensal',
                 'Percentual',
                 'Brasil',
                 'Brasil',
                 'Taxa de desocupação')
)


lista_nova <- list()

# alterar o codigo das series
for(i in c(1:length(listaSeries))){

  # Split the text at commas 
  split_text <- unlist(strsplit(listaSeries[[i]], "','", fixed = TRUE))
  
  # substituir o numero pela combinacao de data e hora
  split_text[[1]] <- sub("\\b\\d{6}\\b", paste0("'numero': ", "'",UUIDgenerate(),"'"), split_text[[1]])
  
  # substituir a primeira virgula por "nome"
  split_text[[1]] <- paste0(sub("','", "', 'nome': '", split_text[[1]]),"'")
  
  # trocar nome cadastroSeries pelo nome que o banco de dados aceita
  split_text[[1]] <- sub("cadastroSeries\\(","<String, dynamic>{",split_text[[1]])
  
  # substituir a primeira virgula por "nomeCompleto"
  split_text[[2]] <- paste0("'nomeCompleto': ", "'", split_text[[2]], "'")
  
  # substituir a primeira virgula por "descricao"
  split_text[[3]] <- paste0("'descricao': ", "'", split_text[[3]], "'")
  
  # substituir a primeira virgula por "formato"
  split_text[[4]] <- paste0("'formato': ", "'", split_text[[4]], "'")
  
  # substituir a primeira virgula por "fonte"
  split_text[[5]] <- paste0("'fonte': ", "'", split_text[[5]], "'")
  

  split_text_7 <- unlist(strsplit(split_text[[6]], ",", fixed = TRUE))
  split_text_7[[1]] <- paste0("'urlAPI': ", "'", split_text_7[[1]])
  split_text_7[[2]] <- paste0("'idAssunto': ", split_text_7[[2]])
  split_text_7[[3]] <- paste0("'periodicidade': ", split_text_7[[3]],"'")
  
  split_text[[6]] <- paste(split_text_7, collapse = ",")
  
  # substituir a primeira virgula por "metrica"
  split_text[[7]] <- paste0("'metrica': ", "'", split_text[[7]], "'")
  
  # substituir a primeira virgula por "nivelGeografico"
  split_text[[8]] <- paste0("'nivelGeografico': ", "'", split_text[[8]], "'")
  
  # substituir a primeira virgula por "localidades"
  split_text[[9]] <- paste0("'localidades': ", "'", split_text[[9]], "'")
  
  # substituir a primeira virgula por "categoria"
  split_text[[10]] <- paste0("'categoria': ", "'", split_text[[10]])
  
  # substituir o parenteses no final
  split_text[[10]] <- sub("'),", "'},", split_text[[10]])
  
  lista_nova[[i]] <- paste(split_text, collapse = ",")
}

# codigo <- paste(Sys.Date(), format(Sys.time(), "%H:%M:%OS6"), sep = "_")

# transformar em data.frame
teste2 <- do.call("rbind",lista_nova)
teste2 <- as.data.frame(teste2)
# apagar o numero das linhas
row.names(teste2) <- NULL
# exportar como csv
write.csv(teste2, file="C:/Users/Kleber/Documents/mercado_trabalho.csv", row.names = F)
     



