library(uuid)


# criar a funcao que simula a classe cadastroSeries existente no app
cadastroSeries <- function(numero, nome, nomeCompleto, descricao, formato, fonte, urlAPI, idAssunto, periodicidade, metrica, nivelGeografico, localidades,
                           categoria){
  
  return(paste0("cadastroSeries(",numero,",'",nome,"','",nomeCompleto,"','",descricao,"','",formato,"','",fonte,"','",urlAPI,"',",idAssunto,",'",periodicidade,"','",metrica,
                "','",nivelGeografico,"','",localidades,"','",categoria,"'),"))
  
}


listaSeries <- list(
  cadastroSeries(500001,
                 'Meta de inflação',
                 'Meta de inflação',
                 'Meta anual de inflação.',
                 '%',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.13521/dados?formato=json',
                 5,
                 'anual',
                 'Meta de inflação',
                 'Brasil',
                 'Brasil',
                 'Meta de inflação'),
  cadastroSeries(500001,
                 'Taxa SELIC',
                 'Meta Selic definida pelo Copom',
                 'A taxa Selic é a taxa básica de juros da economia, que influencia outras taxas de juros do país, como taxas de empréstimos, financiamentos e aplicações financeiras. A definição da taxa Selic é o principal instrumento de política monetária utilizado pelo Banco Central (BC) para controlar a inflação. A Selic é a taxa de juros média praticada nas operações compromissadas com títulos públicos federais com prazo de um dia útil. O BC realiza operações no mercado de títulos públicos para que a taxa Selic efetiva esteja em linha com a meta da taxa Selic, que é definida pelo Comitê de Política Monetária (Copom) do BC.',
                 '%',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.432/dados?formato=json',
                 5,
                 'diária',
                 'Meta Selic definida pelo Copom',
                 'Brasil',
                 'Brasil',
                 'Meta Selic definida pelo Copom'),
  cadastroSeries(500002,
                 'Agregados monetários',
                 'Papel moeda em circulação (saldo diário)',
                 'Papel moeda em circulação.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1780/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Papel moeda em circulação'),
  cadastroSeries(500003,
                 'Agregados monetários',
                 'Reservas bancárias (saldo diário)',
                 'Reservas das instituições financeiras depositados no Banco Central e em caixa.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1781/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Reservas bancárias'),
  cadastroSeries(500004,
                 'Agregados monetários',
                 'Base monetária restrita (saldo diário)',
                 'A base monetária restrita é a soma do papel-moeda em circulação e das reservas bancárias e conta de pagamentos instantâneos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1782/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Base monetária restrita'),
  cadastroSeries(500005,
                 'Agregados monetários',
                 'Papel moeda em circulação (média nos dias úteis do mês)',
                 'Papel moeda em circulação.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1783/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis do mês',
                 'Brasil',
                 'Brasil',
                 'Papel moeda em circulação'),
  cadastroSeries(500006,
                 'Agregados monetários',
                 'Reservas bancárias (média nos dias úteis do mês)',
                 'Reservas das instituições financeiras depositados no Banco Central e em caixa.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1784/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis do mês',
                 'Brasil',
                 'Brasil',
                 'Reservas bancárias'),
  cadastroSeries(500007,
                 'Agregados monetários',
                 'Base monetária restrita (média nos dias úteis do mês)',
                 'A base monetária restrita é a soma do papel-moeda em circulação e das reservas bancárias e conta de pagamentos instantâneos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1785/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis do mês',
                 'Brasil',
                 'Brasil',
                 'Base monetária restrita'),
  cadastroSeries(500008,
                 'Agregados monetários',
                 'Papel moeda em circulação (saldo em final de período)',
                 'Papel moeda em circulação.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1786/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Papel moeda em circulação'),
  cadastroSeries(500009,
                 'Agregados monetários',
                 'Reservas bancárias (saldo em final de período)',
                 'Reservas das instituições financeiras depositados no Banco Central e em caixa.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1787/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Reservas bancárias'),
  cadastroSeries(500010,
                 'Agregados monetários',
                 'Base monetária restrita (saldo em final de período)',
                 'A base monetária restrita é a soma do papel-moeda em circulação e das reservas bancárias e conta de pagamentos instantâneos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1788/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Base monetária restrita'),
  cadastroSeries(500011,
                 'Agregados monetários',
                 'Base monetária restrita (saldo em final de período) - sazonalmente ajustado',
                 'A base monetária restrita é a soma do papel-moeda em circulação e das reservas bancárias e conta de pagamentos instantâneos. O método empregado no processo de ajuste sazonal é o X-13 Arima Seats.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.27840/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Base monetária restrita - sazonalmente ajustado'),
  cadastroSeries(500012,
                 'Fatores condicionantes da base monetária',
                 'Operações com títulos públicos federais - Total (saldo diário)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1789/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais'),
  cadastroSeries(500013,
                 'Fatores condicionantes da base monetária',
                 'Tesouro Nacional - conta única (saldo diário)',
                 'Refere-se aos saques e depósitos na conta única do Tesouro Nacional (TN) junto ao Bacen, exceto os referentes às operações com títulos da dívida mobiliária e àquelas entre o TN e a autoridade monetária. Neste item incluem-se, também, as movimentações do Instituto Nacional do Seguro Social (INSS).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1790/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Tesouro Nacional - conta única'),
  cadastroSeries(500014,
                 'Fatores condicionantes da base monetária',
                 'Operações com o setor externo (saldo diário)',
                 'Expressa, principalmente, as transações de compra e venda de moeda estrangeira realizadas pelo Bacen no mercado interbancário de câmbio. Inclui ainda, o trânsito de recursos de organismos internacionais destinados à manutenção de suas representações no Brasil e a projetos de saneamento básico, geralmente de prefeituras e governos estaduais.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1791/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Operações com o setor externo'),
  cadastroSeries(500015,
                 'Fatores condicionantes da base monetária',
                 'Depósitos de instituições financeiras (saldo diário)',
                 'Trata-se do recolhimento compulsório incidente sobre os fundos de investimento financeiro.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1795/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Depósitos de instituições financeiras'),
  cadastroSeries(500016,
                 'Fatores condicionantes da base monetária',
                 'Autoridade Monetária - outras operações (saldo diário)',
                 'Referem-se às demais operações entre o Bacen e a sociedade. Inclui, entre outros, as multas, os resultados de processos de liquidação de instituição financeira junto ao Departamento de Liquidações Extrajudiciais (Deliq) e as despesas e receitas do Bacen relativas às transações não financeiras (manutenção, folha de pagamentos, gastos do meio circulante, etc).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1798/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Autoridade Monetária - outras operações'),
  cadastroSeries(500017,
                 'Fatores condicionantes da base monetária',
                 'Operações com títulos públicos federais - Total (média nos dias úteis no mês)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1799/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis no mês',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais'),
  cadastroSeries(500018,
                 'Fatores condicionantes da base monetária',
                 'Tesouro Nacional - conta única (média nos dias úteis no mês)',
                 'Refere-se aos saques e depósitos na conta única do Tesouro Nacional (TN) junto ao Bacen, exceto os referentes às operações com títulos da dívida mobiliária e àquelas entre o TN e a autoridade monetária. Neste item incluem-se, também, as movimentações do Instituto Nacional do Seguro Social (INSS).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1800/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis no mês',
                 'Brasil',
                 'Brasil',
                 'Tesouro Nacional - conta única'),
  cadastroSeries(500019,
                 'Fatores condicionantes da base monetária',
                 'Operações com o setor externo (média nos dias úteis no mês)',
                 'Expressa, principalmente, as transações de compra e venda de moeda estrangeira realizadas pelo Bacen no mercado interbancário de câmbio. Inclui ainda, o trânsito de recursos de organismos internacionais destinados à manutenção de suas representações no Brasil e a projetos de saneamento básico, geralmente de prefeituras e governos estaduais.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1801/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis no mês',
                 'Brasil',
                 'Brasil',
                 'Operações com o setor externo'),
  cadastroSeries(500020,
                 'Fatores condicionantes da base monetária',
                 'Depósitos de instituições financeiras (média nos dias úteis no mês)',
                 'Trata-se do recolhimento compulsório incidente sobre os fundos de investimento financeiro.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1805/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis no mês',
                 'Brasil',
                 'Brasil',
                 'Depósitos de instituições financeiras'),
  cadastroSeries(500021,
                 'Fatores condicionantes da base monetária',
                 'Autoridade Monetária - outras operações (média nos dias úteis no mês)',
                 'Referem-se às demais operações entre o Bacen e a sociedade. Inclui, entre outros, as multas, os resultados de processos de liquidação de instituição financeira junto ao Departamento de Liquidações Extrajudiciais (Deliq) e as despesas e receitas do Bacen relativas às transações não financeiras (manutenção, folha de pagamentos, gastos do meio circulante, etc).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1808/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias úteis no mês',
                 'Brasil',
                 'Brasil',
                 'Autoridade Monetária - outras operações'),
  cadastroSeries(500022,
                 'Fatores condicionantes da base monetária',
                 'Operações com títulos públicos federais - Total (saldo em final de período)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1809/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais'),
  cadastroSeries(500023,
                 'Fatores condicionantes da base monetária',
                 'Tesouro Nacional - conta única (saldo em final de período)',
                 'Refere-se aos saques e depósitos na conta única do Tesouro Nacional (TN) junto ao Bacen, exceto os referentes às operações com títulos da dívida mobiliária e àquelas entre o TN e a autoridade monetária. Neste item incluem-se, também, as movimentações do Instituto Nacional do Seguro Social (INSS).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1810/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Tesouro Nacional - conta única'),
  cadastroSeries(500024,
                 'Fatores condicionantes da base monetária',
                 'Operações com o setor externo (saldo em final de período)',
                 'Expressa, principalmente, as transações de compra e venda de moeda estrangeira realizadas pelo Bacen no mercado interbancário de câmbio. Inclui ainda, o trânsito de recursos de organismos internacionais destinados à manutenção de suas representações no Brasil e a projetos de saneamento básico, geralmente de prefeituras e governos estaduais.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1811/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Operações com o setor externo'),
  cadastroSeries(500025,
                 'Fatores condicionantes da base monetária',
                 'Depósitos de instituições financeiras (saldo em final de período)',
                 'Trata-se do recolhimento compulsório incidente sobre os fundos de investimento financeiro.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1815/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Depósitos de instituições financeiras'),
  cadastroSeries(500026,
                 'Fatores condicionantes da base monetária',
                 'Autoridade Monetária - outras operações (saldo em final de período)',
                 'Referem-se às demais operações entre o Bacen e a sociedade. Inclui, entre outros, as multas, os resultados de processos de liquidação de instituição financeira junto ao Departamento de Liquidações Extrajudiciais (Deliq) e as despesas e receitas do Bacen relativas às transações não financeiras (manutenção, folha de pagamentos, gastos do meio circulante, etc).',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1818/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Autoridade Monetária - outras operações'),
  cadastroSeries(500027,
                 'Redesconto',
                 'Redesconto (saldo diário)',
                 'O redesconto bancário é uma medida em que o Banco Central empresta dinheiro aos bancos comerciais, quando estes se encontram com poucos recursos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.12481/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Redesconto'),
  cadastroSeries(500028,
                 'Redesconto',
                 'Redesconto (média dos dias úteis)',
                 'O redesconto bancário é uma medida em que o Banco Central empresta dinheiro aos bancos comerciais, quando estes se encontram com poucos recursos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.12483/dados?formato=json',
                 5,
                 'mensal',
                 'Média dos dias úteis)',
                 'Brasil',
                 'Brasil',
                 'Redesconto'),
  cadastroSeries(500029,
                 'Redesconto',
                 'Redesconto (saldo em final de período)',
                 'O redesconto bancário é uma medida em que o Banco Central empresta dinheiro aos bancos comerciais, quando estes se encontram com poucos recursos.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.12484/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Redesconto'),
  cadastroSeries(500030,
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas (saldo diário)',
                 'São operações em que o Banco Central provê recursos às instituições financeiras.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28723/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas'),
  cadastroSeries(500031,
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas (saldo em final de período)',
                 'São operações em que o Banco Central provê recursos às instituições financeiras.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28724/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas'),
  cadastroSeries(500032,
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas (média nos dias uties no mês)',
                 'São operações em que o Banco Central provê recursos às instituições financeiras.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28727/dados?formato=json',
                 5,
                 'mensal',
                 'Média nos dias uties no mês',
                 'Brasil',
                 'Brasil',
                 'Linhas Temporárias Especiais de Liquidez com Debêntures e Letras Financeiras Garantidas'),
  cadastroSeries(500033,
                 'Operações com títulos públicos federais – mercado primário',
                 'Operações com títulos públicos federais – mercado primário (saldo diário)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29003/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais – mercado primário'),
  cadastroSeries(500034,
                 'Operações com títulos públicos federais – mercado primário',
                 'Operações com títulos públicos federais – mercado primário (saldo em final de período)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29004/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais – mercado primário'),
  cadastroSeries(500035,
                 'Operações com títulos públicos federais – mercado secundário',
                 'Operações com títulos públicos federais – mercado secundário (saldo diário)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29005/dados?formato=json',
                 5,
                 'diária',
                 'Saldo diário',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais – mercado secundário'),
  cadastroSeries(500036,
                 'Operações com títulos públicos federais – mercado secundário',
                 'Operações com títulos públicos federais – mercado secundário (saldo em final de período)',
                 'Referem-se às operações com títulos da dívida mobiliária federal realizadas pelo Bacen junto a sociedade, que tenham impacto monetário. Os títulos podem ser tanto de emissão do Tesouro Nacional quanto do Bacen e as operações podem ser tanto definitivas quanto com cláusula de recompra e revenda.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.29006/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Operações com títulos públicos federais – mercado secundário'),
  cadastroSeries(500037,
                 'Multiplicador e coeficientes de comportamento monetário',
                 'Comportamento do público - C',
                 'A fórmula de cálculo desta variável é C = PMPP / M1, onde C = Preferência do público por papel-moeda; PMPP = Papel-moeda em poder do público; e M1 = Meios de pagamento.',
                 'índice',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7530/dados?formato=json',
                 5,
                 'mensal',
                 'Índice',
                 'Brasil',
                 'Brasil',
                 'Comportamento do público - C'),
  cadastroSeries(500038,
                 'Multiplicador e coeficientes de comportamento monetário',
                 'Comportamento do público - D',
                 'A fórmula de cálculo desta variável é D = DV / M1, onde D = Preferência do público por depósitos à vista; DV = Depósitos à vista; e M1 = Meios de pagamento.',
                 'índice',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7531/dados?formato=json',
                 5,
                 'mensal',
                 'Índice',
                 'Brasil',
                 'Brasil',
                 'Comportamento do público - D'),
  cadastroSeries(500039,
                 'Multiplicador e coeficientes de comportamento monetário',
                 'Comportamento dos bancos - R1',
                 'A fórmula de cálculo desta variável é R1 = CX / DV, onde R1 = Taxa de encaixe em moeda corrente; CX = Encaixe em moeda corrente = Papel moeda emitido - papel moeda em poder do público; e DV = Depósitos à vista.',
                 'índice',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7532/dados?formato=json',
                 5,
                 'mensal',
                 'Índice',
                 'Brasil',
                 'Brasil',
                 'Comportamento dos bancos - R1'),
  cadastroSeries(500040,
                 'Multiplicador e coeficientes de comportamento monetário',
                 'Comportamento dos bancos - R2',
                 'A fórmula de cálculo desta variável é R2 = RB / DV, onde R2 = Taxa de reservas bancárias; RB = Reservas bancárias; e DV = Depósitos à vista.',
                 'índice',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7533/dados?formato=json',
                 5,
                 'mensal',
                 'Índice',
                 'Brasil',
                 'Brasil',
                 'Comportamento dos bancos - R2'),
  cadastroSeries(500041,
                 'Multiplicador e coeficientes de comportamento monetário',
                 'Multiplicador monetário - K',
                 'A fórmula de cálculo desta variável é K = 1 / [C+D(R1+R2)] = M1 / B, onde C = Preferência do público por papel-moeda; D = Preferência do público por depósitos à vista; R1 = Taxa de encaixe em moeda corrente; R2 = Taxa de reservas bancárias; M1 = Meios de pagamento; e B = Base monetária.',
                 'índice',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7534/dados?formato=json',
                 5,
                 'mensal',
                 'Índice',
                 'Brasil',
                 'Brasil',
                 'Multiplicador monetário - K'),
  cadastroSeries(500042,
                 'Base monetária ampliada',
                 'Depósitos compulsórios em espécie',
                 'Trata-se de parcela do dinheiro dos correntistas que os bancos são obrigados a manter depositada no Banco Central.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1828/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Depósitos compulsórios em espécie'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Títulos do Tesouro Nacional - carteira do mercado/Selic',
                 'Títulos do Tesouro Nacional em mercado e no sistema Selic.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1831/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Títulos do Tesouro Nacional - carteira do mercado/Selic'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Títulos do Tesouro Nacional-financiamento líquido/Selic',
                 'Títulos do Tesouro Nacional líquidos de financiamento.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1832/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Títulos do Tesouro Nacional-financiamento líquido/Selic'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Base Monetária Ampliada',
                 'O conceito inclui, além da base restrita, obrigações do Banco Central e do Tesouro Nacional - mais precisamente, fundos mantidos em depósitos de reserva e posições de custódia de títulos federais, tanto do Banco Central quanto do Tesouro Nacional. As posições de custódia são o resultado da adição das posições de carteira às posições líquidas de financiamento dos títulos federais concedidos pela Autoridade Monetária e as posições mencionadas na Resolução nº 2308 (28.8.1996). As LBC-E são excluídas dos títulos do Banco Central.',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1833/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Base Monetária Ampliada'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Títulos públicos federais - total',
                 'Total de títulos públicos federais',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.7535/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Títulos públicos federais - total'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Depósitos voluntários remunerados',
                 'Depósitos voluntários remunerados, conforme Resolução BCB nr. 129, de 19/08/21',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28964/dados?formato=json',
                 5,
                 'mensal',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Depósitos voluntários remunerados'),
  cadastroSeries(500043,
                 'Base monetária ampliada',
                 'Depósitos voluntários remunerados',
                 'Depósitos voluntários remunerados, conforme Resolução BCB nr. 129, de 19/08/21',
                 'milhares da unidade monetária vigente',
                 'Banco Central do Brasil',
                 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.28965/dados?formato=json',
                 5,
                 'diária',
                 'Saldo em final de período',
                 'Brasil',
                 'Brasil',
                 'Depósitos voluntários remunerados')
  
)


lista_nova <- list()

# alterar o codigo das series
for(i in c(1:length(listaSeries))){

  # Split the text at commas 
  split_text <- unlist(strsplit(listaSeries[[i]], "','", fixed = TRUE))
  
  # substituir o numero pela combinacao de data e hora
  split_text[[1]] <- sub("\\b\\d{6}\\b", paste0("'numero': ", "'",UUIDgenerate(),"'"), split_text[[1]])
  
  # substituir a primeira virgula por "nome"
  split_text[[1]] <- paste0(sub("','", "', 'nome': '", split_text[[1]]),"'")
  
  # trocar nome cadastroSeries pelo nome que o banco de dados aceita
  split_text[[1]] <- sub("cadastroSeries\\(","<String, dynamic>{",split_text[[1]])
  
  # substituir a primeira virgula por "nomeCompleto"
  split_text[[2]] <- paste0("'nomeCompleto': ", "'", split_text[[2]], "'")
  
  # substituir a primeira virgula por "descricao"
  split_text[[3]] <- paste0("'descricao': ", "'", split_text[[3]], "'")
  
  # substituir a primeira virgula por "formato"
  split_text[[4]] <- paste0("'formato': ", "'", split_text[[4]], "'")
  
  # substituir a primeira virgula por "fonte"
  split_text[[5]] <- paste0("'fonte': ", "'", split_text[[5]], "'")
  

  split_text_7 <- unlist(strsplit(split_text[[6]], ",", fixed = TRUE))
  split_text_7[[1]] <- paste0("'urlAPI': ", "'", split_text_7[[1]])
  split_text_7[[2]] <- paste0("'idAssunto': ", split_text_7[[2]])
  split_text_7[[3]] <- paste0("'periodicidade': ", split_text_7[[3]],"'")
  
  split_text[[6]] <- paste(split_text_7, collapse = ",")
  
  # substituir a primeira virgula por "metrica"
  split_text[[7]] <- paste0("'metrica': ", "'", split_text[[7]], "'")
  
  # substituir a primeira virgula por "nivelGeografico"
  split_text[[8]] <- paste0("'nivelGeografico': ", "'", split_text[[8]], "'")
  
  # substituir a primeira virgula por "localidades"
  split_text[[9]] <- paste0("'localidades': ", "'", split_text[[9]], "'")
  
  # substituir a primeira virgula por "categoria"
  split_text[[10]] <- paste0("'categoria': ", "'", split_text[[10]])
  
  # substituir o parenteses no final
  split_text[[10]] <- sub("'),", "'},", split_text[[10]])
  
  lista_nova[[i]] <- paste(split_text, collapse = ",")
}

# codigo <- paste(Sys.Date(), format(Sys.time(), "%H:%M:%OS6"), sep = "_")

# transformar em data.frame
teste2 <- do.call("rbind",lista_nova)
teste2 <- as.data.frame(teste2)
# apagar o numero das linhas
row.names(teste2) <- NULL
# exportar como csv
write.csv(teste2, file="C:/Users/Kleber/Documents/dados_monetarios_1.csv", row.names = F)
     



